"""
Django settings for flowdocs project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from core.runtime_config import validate_redis_url
from core.environment import EnvironmentIdentity
from core.side_effects import resolve_email_backend, validate_production_safety
from vaultops.runtime_control import (
    RuntimeControlError,
    resolve_runtime_from_env,
)


def _env_positive_int(name, default):
    raw_value = os.getenv(name, str(default))
    try:
        value = int(raw_value)
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be an integer') from exc
    if value < 1:
        raise ImproperlyConfigured(f'{name} must be a positive integer')
    return value


def _env_positive_decimal(name, default):
    raw_value = os.getenv(name, str(default)).strip()
    try:
        value = Decimal(raw_value)
    except (InvalidOperation, ValueError) as exc:
        raise ImproperlyConfigured(f'{name} must be a positive number') from exc
    if not value.is_finite() or value <= 0:
        raise ImproperlyConfigured(f'{name} must be a positive number')
    return value


def _env_bool(name, default=False):
    raw_value = os.getenv(name, "1" if default else "0").strip().lower()
    if raw_value in {"1", "true", "yes", "on"}:
        return True
    if raw_value in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(f'{name} must be a boolean')


def _env_nonnegative_int(name, default=0):
    raw_value = os.getenv(name, str(default)).strip()
    try:
        value = int(raw_value)
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be an integer') from exc
    if value < 0:
        raise ImproperlyConfigured(f'{name} must be zero or greater')
    return value


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))
DATA_ROOT = Path(os.getenv('DATA_ROOT', str(BASE_DIR / 'data')))
DATA_CONTROL_ROOT = Path(
    os.getenv('DATA_CONTROL_ROOT', str(DATA_ROOT / 'data-control'))
)
CONTROL_DB_PATH = Path(
    os.getenv('CONTROL_DB_PATH', str(DATA_CONTROL_ROOT / 'control.sqlite3'))
)
RUNTIME_GENERATIONS_ROOT = Path(
    os.getenv(
        'RUNTIME_GENERATIONS_ROOT',
        str(DATA_ROOT / 'runtime-generations'),
    )
)
try:
    ACTIVE_RUNTIME = resolve_runtime_from_env()
except RuntimeControlError as exc:
    raise ImproperlyConfigured(exc.reason_code) from exc
RUNTIME_GENERATION_ID = (
    ACTIVE_RUNTIME.generation_id if ACTIVE_RUNTIME else ''
)
RUNTIME_MANIFEST_DIGEST = (
    ACTIVE_RUNTIME.manifest_digest if ACTIVE_RUNTIME else ''
)
#--------------for gemini Model---------------------
# GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')



#---------------------For OpenApi-----------------------------------------------------
import environ

env = environ.Env()
environ.Env.read_env()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_EMBED_MODEL = os.getenv("OPENAI_EMBED_MODEL", "text-embedding-3-small")
OPENAI_CHAT_MODEL = os.getenv("OPENAI_CHAT_MODEL", "gpt-4o-mini")
#OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_allow_insecure_defaults = os.getenv('ALLOW_INSECURE_DEFAULTS', '0').lower() == '1'
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if _allow_insecure_defaults:
        SECRET_KEY = 'django-insecure-local-only-change-me'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]
if '*' in ALLOWED_HOSTS and not (DEBUG and _allow_insecure_defaults):
    raise ImproperlyConfigured('Wildcard ALLOWED_HOSTS is only allowed for local development')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',
    'vaultops',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'vaultops.middleware.SourceMutationBarrierMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flowdocs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.legal_last_updated',
            ],
        },
    },
]

WSGI_APPLICATION = 'flowdocs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Media lifecycle services reject caller-owned transactions so their
        # committed application row/audit can safely precede the control epoch.
        'ATOMIC_REQUESTS': False,
        'NAME': str(
            ACTIVE_RUNTIME.database_path
            if ACTIVE_RUNTIME
            else os.getenv('SQLITE_DB_PATH', str(DATA_ROOT / 'db.sqlite3'))
        ),
    },
    'control': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(CONTROL_DB_PATH),
    },
}

DATABASE_ROUTERS = ['vaultops.router.VaultControlRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.getenv('STATIC_ROOT', str(DATA_ROOT / 'staticfiles')))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = (
    ACTIVE_RUNTIME.media_root
    if ACTIVE_RUNTIME
    else Path(os.getenv('MEDIA_ROOT', str(DATA_ROOT / 'media')))
)

AUTH_USER_MODEL = 'core.CustomUser'
# OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')


from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('en', 'English'),
    ('mr', 'Marathi'),
]

USE_I18N = True
USE_L10N = True

LOCALE_PATHS = [
    BASE_DIR / "locale",  # Canonical catalogs live under flowdocs/locale only.
]


LOGIN_URL = '/login/'

# Cache configuration. Redis is shared by Gunicorn workers in production;
# local memory remains available for explicit local development.
REDIS_URL = validate_redis_url(
    os.getenv('REDIS_URL', ''),
    allow_loopback=_allow_insecure_defaults,
)

PUBLIC_SEARCH_ENABLED = os.getenv('PUBLIC_SEARCH_ENABLED', '1').lower() in {'1', 'true', 'yes'}
DISPLAY_SERVICE_FOOTER = os.getenv('DISPLAY_SERVICE_FOOTER', '1').lower() in {'1', 'true', 'yes'}
_public_search_folder_ids = os.getenv('PUBLIC_SEARCH_FOLDER_IDS', '').strip().lower()
PUBLIC_SEARCH_ALL_FOLDERS = _public_search_folder_ids in {'', 'all'}
try:
    PUBLIC_SEARCH_FOLDER_IDS = frozenset(
        int(value.strip())
        for value in _public_search_folder_ids.split(',')
        if value.strip()
    ) if not PUBLIC_SEARCH_ALL_FOLDERS else frozenset()
except ValueError as exc:
    raise ImproperlyConfigured(
        'PUBLIC_SEARCH_FOLDER_IDS must be all or a comma-separated list of integers'
    ) from exc

if PUBLIC_SEARCH_ENABLED and not PUBLIC_SEARCH_ALL_FOLDERS and not PUBLIC_SEARCH_FOLDER_IDS:
    raise ImproperlyConfigured(
        'PUBLIC_SEARCH_FOLDER_IDS is required when PUBLIC_SEARCH_ENABLED is enabled'
    )

PUBLIC_SEARCH_MAX_WORDS = _env_positive_int('PUBLIC_SEARCH_MAX_WORDS', 30)
PUBLIC_SEARCH_RATE_LIMIT = _env_positive_int('PUBLIC_SEARCH_RATE_LIMIT', 30)
PUBLIC_SEARCH_RATE_WINDOW = _env_positive_int('PUBLIC_SEARCH_RATE_WINDOW', 60)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache' if REDIS_URL else 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': REDIS_URL or 'unique-snowflake',
    }
}

CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if origin.strip()]

CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', str(not DEBUG)).lower() == 'true'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False


# File upload settings. MAX_FILE_SIZE_MB is the operator-facing setting. The
# conversion uses 1024**2 bytes so the historical 10 MB default remains exact.
_BYTES_PER_MB = 1024 * 1024
_legacy_max_file_size = os.getenv('MAX_FILE_SIZE')
_configured_max_file_size_mb = os.getenv('MAX_FILE_SIZE_MB')
if _configured_max_file_size_mb is not None:
    MAX_FILE_SIZE_MB = _env_positive_decimal('MAX_FILE_SIZE_MB', 10)
    MAX_FILE_SIZE = int(
        (MAX_FILE_SIZE_MB * _BYTES_PER_MB).to_integral_value(rounding=ROUND_HALF_UP)
    )
    if _legacy_max_file_size is not None:
        _legacy_max_file_size_bytes = _env_positive_int('MAX_FILE_SIZE', MAX_FILE_SIZE)
        if _legacy_max_file_size_bytes != MAX_FILE_SIZE:
            raise ImproperlyConfigured(
                'MAX_FILE_SIZE conflicts with MAX_FILE_SIZE_MB; remove the deprecated '
                'MAX_FILE_SIZE setting'
            )
else:
    # Compatibility for one deployment cycle. New environments must define
    # MAX_FILE_SIZE_MB; this branch preserves existing byte-based deployments.
    MAX_FILE_SIZE = _env_positive_int('MAX_FILE_SIZE', 10 * _BYTES_PER_MB)
    MAX_FILE_SIZE_MB = (
        Decimal(MAX_FILE_SIZE) / Decimal(_BYTES_PER_MB)
    ).normalize()
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_FILE_SIZE
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_FILE_SIZE

# Read-only inventory, activation, recovery, and candidate verification must
# accommodate canonical legacy media without weakening the new-upload policy.
# Keep this byte limit independently bounded so operators cannot accidentally
# turn a larger custody corpus into a larger request-body allowance.
ARTIFACT_INVENTORY_MAX_MEDIA_FILE_BYTES = _env_positive_int(
    'ARTIFACT_INVENTORY_MAX_MEDIA_FILE_BYTES',
    64 * _BYTES_PER_MB,
)

# Retrieval and cache tuning. Keep these conservative unless a release record
# captures the model, vector index, and quality-impact checks together.
PDF_CHUNK_SIZE = _env_positive_int('PDF_CHUNK_SIZE', 1200)
PDF_CHUNK_OVERLAP = _env_positive_int('PDF_CHUNK_OVERLAP', 200)
MAX_CONTEXT_WORDS = _env_positive_int('MAX_CONTEXT_WORDS', 2500)
TOP_K_CHUNKS = _env_positive_int('TOP_K_CHUNKS', 5)
EMBEDDING_TTL = _env_positive_int('EMBEDDING_TTL', 60 * 60 * 24 * 7)
SEARCH_CACHE_TTL = _env_positive_int('SEARCH_CACHE_TTL', 60 * 10)

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Default session age 2 weeks (seconds)
SESSION_COOKIE_AGE = 1209600


SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', str(not DEBUG)).lower() == 'true'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() == 'true'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False').lower() == 'true'

EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

FAISS_INDEX_DIR = (
    ACTIVE_RUNTIME.faiss_index_dir
    if ACTIVE_RUNTIME
    else Path(os.getenv('FAISS_INDEX_DIR', str(DATA_ROOT / 'faiss_indexes')))
)
CHROMA_DIR = (
    ACTIVE_RUNTIME.chroma_dir
    if ACTIVE_RUNTIME
    else Path(os.getenv('CHROMA_DIR', str(DATA_ROOT / 'chroma_db')))
)
BACKUP_DIR = Path(os.getenv('BACKUP_DIR', str(DATA_ROOT / 'backups')))
RECOVERY_SET_ROOT = Path(
    os.getenv('RECOVERY_SET_ROOT', str(BACKUP_DIR / 'recovery-sets'))
)
LOCAL_INDEX_MAINTENANCE_ENABLED = _env_bool(
    'LOCAL_INDEX_MAINTENANCE_ENABLED', False
)
FORCE_REINDEX_ENABLED = _env_bool('FORCE_REINDEX_ENABLED', False)
EXTERNAL_EMBEDDINGS_ENABLED = _env_bool('EXTERNAL_EMBEDDINGS_ENABLED', False)
MAINTENANCE_WORKSPACE_ROOT = Path(
    os.getenv(
        'MAINTENANCE_WORKSPACE_ROOT',
        str(DATA_CONTROL_ROOT / 'maintenance-workspaces'),
    )
)
MAINTENANCE_JOB_TIMEOUT_SECONDS = _env_positive_int(
    'MAINTENANCE_JOB_TIMEOUT_SECONDS', 7200
)
MAINTENANCE_WORKER_HEARTBEAT_PATH = Path(
    os.getenv(
        'MAINTENANCE_WORKER_HEARTBEAT_PATH',
        str(DATA_CONTROL_ROOT / 'runtime' / 'maintenance-worker.heartbeat'),
    )
)
MAINTENANCE_WORKER_HEARTBEAT_MAX_AGE_SECONDS = _env_positive_int(
    'MAINTENANCE_WORKER_HEARTBEAT_MAX_AGE_SECONDS', 30
)
MAINTENANCE_WORKER_READINESS_REQUIRED = _env_bool(
    'MAINTENANCE_WORKER_READINESS_REQUIRED', True
)
MAINTENANCE_CANDIDATE_EXECUTION = _env_bool(
    'MAINTENANCE_CANDIDATE_EXECUTION', False
)
PDF_CACHE_DIR = (
    ACTIVE_RUNTIME.pdf_cache_dir
    if ACTIVE_RUNTIME
    else Path(os.getenv('PDF_CACHE_DIR', str(DATA_ROOT / 'pdf_cache')))
)

# Vault Active Sync remains disabled unless every required switch is explicit.
VAULT_SYNC_ENABLED = _env_bool('VAULT_SYNC_ENABLED', False)
VAULT_MUTATION_TRACKING_ENABLED = _env_bool(
    'VAULT_MUTATION_TRACKING_ENABLED', VAULT_SYNC_ENABLED
)
_vault_sync_mode = os.getenv(
    'VAULT_SYNC_MODE',
    os.getenv('BACKUP_SYNC_MODE', 'manual'),
).strip().lower()
if _vault_sync_mode in {'event-driven', 'hybrid'}:
    import warnings
    warnings.warn(
        f'VAULT_SYNC_MODE={_vault_sync_mode} is deprecated; using continuous_coalesced',
        RuntimeWarning,
    )
    _vault_sync_mode = 'continuous_coalesced'
if _vault_sync_mode not in {
    'disabled', 'manual', 'scheduled', 'continuous_coalesced'
}:
    raise ImproperlyConfigured(
        'VAULT_SYNC_MODE must be disabled, manual, scheduled, or continuous_coalesced'
    )
VAULT_SYNC_MODE = _vault_sync_mode
VAULT_SYNC_PROMOTION_MODE = os.getenv(
    'VAULT_SYNC_PROMOTION_MODE', 'manual'
).strip().lower()
if VAULT_SYNC_PROMOTION_MODE not in {
    'publish_only', 'manual', 'auto_after_validation'
}:
    raise ImproperlyConfigured(
        'VAULT_SYNC_PROMOTION_MODE must be publish_only, manual, or auto_after_validation'
    )
VAULT_SYNC_INTERVAL_SECONDS = _env_positive_int(
    'VAULT_SYNC_INTERVAL_SECONDS', 900
)
VAULT_SYNC_QUIET_PERIOD_SECONDS = _env_positive_int(
    'VAULT_SYNC_QUIET_PERIOD_SECONDS', 120
)
VAULT_SYNC_MAX_LAG_SECONDS = _env_positive_int(
    'VAULT_SYNC_MAX_LAG_SECONDS', 3600
)
VAULT_SYNC_MAX_PARALLEL_UPLOADS = _env_positive_int(
    'VAULT_SYNC_MAX_PARALLEL_UPLOADS', 4
)
VAULT_SYNC_MAX_PARALLEL_HASHERS = _env_positive_int(
    'VAULT_SYNC_MAX_PARALLEL_HASHERS', 2
)
VAULT_JOB_HEARTBEAT_SECONDS = _env_positive_int(
    'VAULT_JOB_HEARTBEAT_SECONDS', 15
)
VAULT_JOB_STALE_SECONDS = _env_positive_int('VAULT_JOB_STALE_SECONDS', 90)
VAULT_VALIDATION_MAX_AGE_SECONDS = _env_positive_int(
    'VAULT_VALIDATION_MAX_AGE_SECONDS', 1800
)
VAULT_SNAPSHOT_BARRIER_TIMEOUT_SECONDS = _env_positive_int(
    'VAULT_SNAPSHOT_BARRIER_TIMEOUT_SECONDS', 30
)
VAULT_SNAPSHOT_ROOT = Path(
    os.getenv('VAULT_SNAPSHOT_ROOT', str(DATA_CONTROL_ROOT / 'snapshots'))
)
VAULT_SNAPSHOT_CLEANUP_GRACE_SECONDS = _env_positive_int(
    'VAULT_SNAPSHOT_CLEANUP_GRACE_SECONDS', 120
)
VAULT_SNAPSHOT_CLEANUP_MAX_ITEMS = _env_positive_int(
    'VAULT_SNAPSHOT_CLEANUP_MAX_ITEMS', 8
)
VAULT_SNAPSHOT_CLEANUP_MAX_SCAN_ITEMS = _env_positive_int(
    'VAULT_SNAPSHOT_CLEANUP_MAX_SCAN_ITEMS', 64
)
VAULT_SNAPSHOT_CLEANUP_MAX_BYTES = _env_positive_int(
    'VAULT_SNAPSHOT_CLEANUP_MAX_BYTES', 536_870_912
)
VAULT_SNAPSHOT_CLEANUP_MAX_SECONDS = _env_positive_int(
    'VAULT_SNAPSHOT_CLEANUP_MAX_SECONDS', 5
)
VAULT_SNAPSHOT_FAISS_MAX_VECTORS = _env_positive_int(
    'VAULT_SNAPSHOT_FAISS_MAX_VECTORS', 1_000_000
)
VAULT_SNAPSHOT_FAISS_MAX_DIMENSIONS = _env_positive_int(
    'VAULT_SNAPSHOT_FAISS_MAX_DIMENSIONS', 4096
)
VAULT_SNAPSHOT_FAISS_MAX_BYTES = _env_positive_int(
    'VAULT_SNAPSHOT_FAISS_MAX_BYTES', 536_870_912
)
VAULT_SNAPSHOT_FAISS_MAX_SOURCE_BYTES = _env_positive_int(
    'VAULT_SNAPSHOT_FAISS_MAX_SOURCE_BYTES', 1_073_741_824
)
VAULT_SNAPSHOT_FAISS_MAX_PDF_JSON_BYTES = _env_positive_int(
    'VAULT_SNAPSHOT_FAISS_MAX_PDF_JSON_BYTES', 134_217_728
)
VAULT_SNAPSHOT_FAISS_MAX_PDFS = _env_positive_int(
    'VAULT_SNAPSHOT_FAISS_MAX_PDFS', 100_000
)
VAULT_SNAPSHOT_FAISS_MAX_CHUNKS_PER_PDF = _env_positive_int(
    'VAULT_SNAPSHOT_FAISS_MAX_CHUNKS_PER_PDF', 100_000
)
VAULT_DEFAULT_PROFILE = os.getenv('VAULT_DEFAULT_PROFILE', 'production').strip()
if not VAULT_DEFAULT_PROFILE:
    raise ImproperlyConfigured('VAULT_DEFAULT_PROFILE cannot be empty')
VAULT_ADMIN_MUTATIONS_ENABLED = _env_bool('VAULT_ADMIN_MUTATIONS_ENABLED', False)
VAULT_GC_ENABLED = _env_bool('VAULT_GC_ENABLED', False)
VAULT_RESTORE_ENABLED = _env_bool('VAULT_RESTORE_ENABLED', False)
VAULT_UI_PROFILE_CONFIGURATION_ENABLED = _env_bool(
    'VAULT_UI_PROFILE_CONFIGURATION_ENABLED', False
)
VAULT_UI_SECRET_ENTRY_ENABLED = _env_bool(
    'VAULT_UI_SECRET_ENTRY_ENABLED', False
)
VAULT_PROFILE_ENCRYPTION_KEY = os.getenv(
    'VAULT_PROFILE_ENCRYPTION_KEY', ''
).strip()
VAULT_CREDENTIAL_ALIASES = os.getenv('VAULT_CREDENTIAL_ALIASES', '').strip()
VAULT_ALLOWED_S3_ENDPOINTS = tuple(
    value.strip().rstrip('/')
    for value in os.getenv('VAULT_ALLOWED_S3_ENDPOINTS', '').split(',')
    if value.strip()
)
VAULT_BLOCK_PRIVATE_S3_ENDPOINTS = _env_bool(
    'VAULT_BLOCK_PRIVATE_S3_ENDPOINTS', True
)
VAULT_ALLOW_HTTP_S3_ENDPOINTS = _env_bool(
    'VAULT_ALLOW_HTTP_S3_ENDPOINTS', False
)
VAULT_INVENTORY_CACHE_SECONDS = _env_positive_int(
    'VAULT_INVENTORY_CACHE_SECONDS', 30
)
VAULT_MAX_MANIFEST_BYTES = _env_positive_int(
    'VAULT_MAX_MANIFEST_BYTES', 8 * 1024 * 1024
)
VAULT_MAX_MANIFEST_OBJECTS = _env_positive_int(
    'VAULT_MAX_MANIFEST_OBJECTS', 100000
)
VAULT_MAX_GENERATION_BYTES = _env_positive_int(
    'VAULT_MAX_GENERATION_BYTES', 500 * 1024 * 1024 * 1024
)
VAULT_RESTORE_ROOT = Path(
    os.getenv(
        'VAULT_RESTORE_ROOT',
        str(DATA_ROOT / 'restore-quarantine'),
    )
)
VAULT_RESTORE_REQUIRE_SANITIZATION = _env_bool(
    'VAULT_RESTORE_REQUIRE_SANITIZATION', True
)
VAULT_RESTORE_ALLOW_REPACKED_RELEASE_MISMATCH = _env_bool(
    'VAULT_RESTORE_ALLOW_REPACKED_RELEASE_MISMATCH', False
)
VAULT_RESTORE_MIN_FREE_BYTES = _env_nonnegative_int(
    'VAULT_RESTORE_MIN_FREE_BYTES', 0
)
VAULT_RESTORE_MIN_FREE_INODES = _env_nonnegative_int(
    'VAULT_RESTORE_MIN_FREE_INODES', 0
)
STAGING_RUNTIME_ACTIVATION_ENABLED = _env_bool(
    'STAGING_RUNTIME_ACTIVATION_ENABLED', False
)
STAGING_INITIAL_ACTIVATION_ENABLED = _env_bool(
    'STAGING_INITIAL_ACTIVATION_ENABLED', False
)
MAINTENANCE_CANDIDATE_PREPARATION_ENABLED = _env_bool(
    'MAINTENANCE_CANDIDATE_PREPARATION_ENABLED', False
)
MAINTENANCE_CANDIDATE_WRITER_MODE = _env_bool(
    'MAINTENANCE_CANDIDATE_WRITER_MODE', False
)
STAGING_ACTIVATION_APPLY_MODE = os.getenv(
    'STAGING_ACTIVATION_APPLY_MODE', 'auto'
).strip().lower()
if STAGING_ACTIVATION_APPLY_MODE not in {'auto', 'pending'}:
    raise ImproperlyConfigured(
        'STAGING_ACTIVATION_APPLY_MODE must be auto or pending'
    )
ACTIVATION_INTENT_SIGNING_KEY = os.getenv(
    'ACTIVATION_INTENT_SIGNING_KEY', ''
)
ACTIVATION_SMOKE_QUERIES_FILE = Path(
    os.getenv(
        'ACTIVATION_SMOKE_QUERIES_FILE',
        str(DATA_CONTROL_ROOT / 'config/activation-smoke-queries.json'),
    )
)
ACTIVATION_RECOVERY_SUPERADMIN_USERNAME = os.getenv(
    'ACTIVATION_RECOVERY_SUPERADMIN_USERNAME', ''
).strip()
ACTIVATION_RECOVERY_SUPERADMIN_PASSWORD = os.getenv(
    'ACTIVATION_RECOVERY_SUPERADMIN_PASSWORD', ''
)
ACTIVATION_SUPERVISOR_POLL_SECONDS = _env_positive_int(
    'ACTIVATION_SUPERVISOR_POLL_SECONDS', 2
)
ACTIVATION_READINESS_TIMEOUT_SECONDS = _env_positive_int(
    'ACTIVATION_READINESS_TIMEOUT_SECONDS', 120
)

# ---- Environment Identity and Side-Effect Safety ----
_env_identity = EnvironmentIdentity.from_env()
_env_errors = _env_identity.validate()
if _env_errors:
    raise ImproperlyConfigured(
        "Environment configuration errors:\n  " + "\n  ".join(_env_errors)
    )

_side_effect_errors = validate_production_safety(_env_identity)
if _side_effect_errors:
    raise ImproperlyConfigured(
        "Side-effect safety violations:\n  " + "\n  ".join(_side_effect_errors)
    )

_resolved_email_backend = resolve_email_backend(_env_identity)
if _resolved_email_backend:
    EMAIL_BACKEND = _resolved_email_backend

ENV_IDENTITY = _env_identity

if ENV_IDENTITY.is_production and STAGING_RUNTIME_ACTIVATION_ENABLED:
    raise ImproperlyConfigured('production_activation_disabled')
if ENV_IDENTITY.is_production and STAGING_INITIAL_ACTIVATION_ENABLED:
    raise ImproperlyConfigured('production_initial_activation_disabled')
if (
    STAGING_INITIAL_ACTIVATION_ENABLED
    and not STAGING_RUNTIME_ACTIVATION_ENABLED
):
    raise ImproperlyConfigured(
        'STAGING_INITIAL_ACTIVATION_ENABLED requires '
        'STAGING_RUNTIME_ACTIVATION_ENABLED'
    )
if (
    MAINTENANCE_CANDIDATE_PREPARATION_ENABLED
    and not (
        STAGING_RUNTIME_ACTIVATION_ENABLED
        or MAINTENANCE_CANDIDATE_WRITER_MODE
    )
):
    raise ImproperlyConfigured(
        'MAINTENANCE_CANDIDATE_PREPARATION_ENABLED requires '
        'STAGING_RUNTIME_ACTIVATION_ENABLED or '
        'MAINTENANCE_CANDIDATE_WRITER_MODE'
    )
if MAINTENANCE_CANDIDATE_WRITER_MODE:
    if ENV_IDENTITY.is_production or ENV_IDENTITY.app_env.value != 'staging':
        raise ImproperlyConfigured(
            'MAINTENANCE_CANDIDATE_WRITER_MODE requires non-production staging'
        )
    if STAGING_RUNTIME_ACTIVATION_ENABLED:
        raise ImproperlyConfigured(
            'MAINTENANCE_CANDIDATE_WRITER_MODE cannot serve an active runtime'
        )
    if len(ACTIVATION_INTENT_SIGNING_KEY) < 32:
        raise ImproperlyConfigured(
            'ACTIVATION_INTENT_SIGNING_KEY must contain at least 32 characters'
        )
    if not VAULT_MUTATION_TRACKING_ENABLED:
        raise ImproperlyConfigured(
            'MAINTENANCE_CANDIDATE_WRITER_MODE requires '
            'VAULT_MUTATION_TRACKING_ENABLED'
        )
if STAGING_RUNTIME_ACTIVATION_ENABLED:
    if ENV_IDENTITY.app_env.value != 'staging':
        raise ImproperlyConfigured(
            'STAGING_RUNTIME_ACTIVATION_ENABLED requires APP_ENV=staging'
        )
    if len(ACTIVATION_INTENT_SIGNING_KEY) < 32:
        raise ImproperlyConfigured(
            'ACTIVATION_INTENT_SIGNING_KEY must contain at least 32 characters'
        )
    if not ACTIVATION_RECOVERY_SUPERADMIN_USERNAME:
        raise ImproperlyConfigured(
            'ACTIVATION_RECOVERY_SUPERADMIN_USERNAME is required'
        )
    if not ACTIVATION_RECOVERY_SUPERADMIN_PASSWORD:
        raise ImproperlyConfigured(
            'ACTIVATION_RECOVERY_SUPERADMIN_PASSWORD is required'
        )

if (
    ENV_IDENTITY.is_production
    and not _allow_insecure_defaults
    and (
        ENV_IDENTITY.dataset_id != 'ai-sahakar-prod'
        or ENV_IDENTITY.authoritative_dataset_id != 'ai-sahakar-prod'
        or (
            ENV_IDENTITY.restore_source_dataset_id
            and ENV_IDENTITY.restore_source_dataset_id != 'ai-sahakar-prod'
        )
    )
):
    raise ImproperlyConfigured(
        'Production dataset identities must use ai-sahakar-prod'
    )
if VAULT_SYNC_ENABLED and not ENV_IDENTITY.is_authoritative_writer:
    raise ImproperlyConfigured(
        'VAULT_SYNC_ENABLED requires an authoritative writer environment'
    )
if (
    ENV_IDENTITY.is_production
    and VAULT_SYNC_PROMOTION_MODE == 'auto_after_validation'
):
    raise ImproperlyConfigured(
        'Automatic vault promotion is disabled in production'
    )
if VAULT_UI_SECRET_ENTRY_ENABLED and not VAULT_PROFILE_ENCRYPTION_KEY:
    raise ImproperlyConfigured(
        'VAULT_UI_SECRET_ENTRY_ENABLED requires VAULT_PROFILE_ENCRYPTION_KEY'
    )
if VAULT_RESTORE_ENABLED and not VAULT_ALLOWED_S3_ENDPOINTS:
    raise ImproperlyConfigured(
        'VAULT_RESTORE_ENABLED requires VAULT_ALLOWED_S3_ENDPOINTS'
    )
if VAULT_RESTORE_ALLOW_REPACKED_RELEASE_MISMATCH:
    if ENV_IDENTITY.is_production or ENV_IDENTITY.app_env.value != 'staging':
        raise ImproperlyConfigured(
            'VAULT_RESTORE_ALLOW_REPACKED_RELEASE_MISMATCH requires '
            'non-production staging'
        )
    if not VAULT_RESTORE_ENABLED or not VAULT_RESTORE_REQUIRE_SANITIZATION:
        raise ImproperlyConfigured(
            'VAULT_RESTORE_ALLOW_REPACKED_RELEASE_MISMATCH requires guarded '
            'restore with sanitization'
        )
