version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    image: dev-one-58pibn:latest
    build: .
    command: sh -c "./start.sh"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - sqlite_data:/app/flowdocs/db.sqlite3   # persist SQLite DB
      - ./backups:/app/backups                # persist backups
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
    restart: unless-stopped   # <--- add this line
volumes:
  static_volume:
  media_volume:
  sqlite_data:
