version: "3.9"

services:
  web:
    build: .
    image: sahakar-final-b7v3vd:latest
    pull_policy: always
    container_name: flowdocs_web
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/flowdocs/media/pdfs        #updated
      - db_volume:/app/flowdocs   
     
    env_file:
      - .env
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  db_volume:

