version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    #image: dev-one-58pibn:latest
    command: ./start.sh
    volumes:
     # - static_volume:/app/staticfiles
     # - media_volume:/app/media
     # - db_volume:/app/flowdocs/flowdocs     # database SQLite volume
     # - backups_volume:/app/backups             # persist backups
     # - chroma_volume:/app/flowdocs/chroma_db  # 

      - static_volume:/app/staticfiles
      - media_volume:/app/flowdocs/media/pdfs        #updated
      - db_volume:/app/flowdocs             # ✅ correct folder (outer)
      - backups_volume:/app/backups
      - chroma_volume:/app/flowdocs/chroma_db
      - faiss_volume:/app/flowdocs/faiss_indexes
     
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  db_volume:
  backups_volume:
  static_volume:
  media_volume:
  chroma_volume:
  faiss_volume:
