# Generated by Django 5.2.16 on 2026-07-26 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultops', '0002_backfill_legacy_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMutationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployment_id', models.CharField(max_length=120, unique=True)),
                ('current_epoch', models.PositiveBigIntegerField(default=0)),
                ('active_mutations', models.PositiveIntegerField(default=0)),
                ('barrier_state', models.CharField(choices=[('open', 'Open'), ('requested', 'Requested'), ('active', 'Active')], default='open', max_length=16)),
                ('barrier_owner_job', models.UUIDField(blank=True, null=True)),
                ('barrier_requested_at', models.DateTimeField(blank=True, null=True)),
                ('barrier_activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_mutation_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vaultjob',
            name='profile_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='syncpolicy',
            name='last_completed_epoch',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncpolicy',
            name='last_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncpolicy',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncpolicy',
            name='pending_epoch',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncpolicy',
            name='warning_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.CreateModel(
            name='MutationJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.CharField(max_length=120)),
                ('epoch', models.PositiveBigIntegerField()),
                ('category', models.CharField(max_length=40)),
                ('relative_path', models.CharField(blank=True, default='', max_length=1000)),
                ('operation', models.CharField(max_length=40)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('observed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['epoch'],
                'indexes': [models.Index(fields=['deployment_id', 'epoch'], name='vaultops_mu_deploym_93d305_idx'), models.Index(fields=['deployment_id', '-observed_at'], name='vaultops_mu_deploym_48feea_idx')],
                'constraints': [models.UniqueConstraint(fields=('deployment_id', 'epoch'), name='vaultops_unique_mutation_epoch')],
            },
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deployment_id', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('copying', 'Copying'), ('barrier', 'Barrier'), ('finalized', 'Finalized'), ('failed', 'Failed')], default='planned', max_length=16)),
                ('initial_epoch', models.PositiveBigIntegerField(default=0)),
                ('included_epoch', models.PositiveBigIntegerField(default=0)),
                ('snapshot_digest', models.CharField(blank=True, default='', max_length=64)),
                ('workspace_path', models.CharField(blank=True, default='', max_length=1000)),
                ('file_count', models.PositiveBigIntegerField(default=0)),
                ('byte_count', models.PositiveBigIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('safe_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_snapshots', to='vaultops.vaultjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
