# Generated by Django 5.2.16 on 2026-07-26 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultops', '0003_sourcemutationstate_syncpolicy_last_completed_epoch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoreworkspace',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restore_workspaces', to='vaultops.vaultjob'),
        ),
        migrations.AddField(
            model_name='restoreworkspace',
            name='downloaded_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restoreworkspace',
            name='downloaded_objects',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restoreworkspace',
            name='pointer_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restoreworkspace',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restoreworkspace',
            name='profile_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restoreworkspace',
            name='safe_error_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='restoreworkspace',
            name='validation_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
