# Generated by Django 5.2.16 on 2026-07-26 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultops', '0004_restore_workspace_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationintent',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activationintent',
            name='committed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activationintent',
            name='safe_error_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='activationintent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activation_intents', to='vaultops.restoreworkspace'),
        ),
    ]
