# Generated by Django 4.2.23 on 2025-09-03 09:57

from django.db import migrations, models
from django.db.migrations.operations.models import RemoveIndex


class ConditionalRemoveIndex(RemoveIndex):
    """
    Custom RemoveIndex that only executes on PostgreSQL.
    On SQLite, the GIN index was never created, so we skip removal.
    """
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Only execute on PostgreSQL
        if schema_editor.connection.vendor == 'postgresql':
            try:
                super().database_forwards(app_label, schema_editor, from_state, to_state)
            except Exception as e:
                # If index doesn't exist, that's fine - ignore the error
                error_str = str(e).lower()
                if 'does not exist' not in error_str and 'no such index' not in error_str:
                    raise
        # For SQLite, do nothing - the index was never created
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # Reverse operation - not needed
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pdffile_content_pdffile_search_vector_and_more'),
    ]

    operations = [
        # Use custom ConditionalRemoveIndex that checks database vendor
        ConditionalRemoveIndex(
            model_name='pdffile',
            name='core_pdffil_search__1650a6_gin',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
