# Generated by Django 4.2.23 on 2025-09-03 09:57

from django.db import migrations, models, connection


def remove_index_safely(apps, schema_editor):
    """
    Remove the GIN index only if it exists (PostgreSQL only).
    SQLite doesn't support GIN indexes, so this index was never created.
    """
    db_vendor = schema_editor.connection.vendor
    if db_vendor == 'postgresql':
        # Only try to remove index on PostgreSQL
        with schema_editor.connection.cursor() as cursor:
            # Check if index exists and remove it
            cursor.execute('DROP INDEX IF EXISTS core_pdffil_search__1650a6_gin')
    # For SQLite, do nothing - the index was never created


def reverse_remove_index(apps, schema_editor):
    """Reverse operation - not needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pdffile_content_pdffile_search_vector_and_more'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to:
        # - Update migration state (remove index from state)
        # - Conditionally execute database operation (only on PostgreSQL)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_index_safely,
                    reverse_remove_index,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='pdffile',
                    name='core_pdffil_search__1650a6_gin',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
