# Generated by Django 4.2.23 on 2025-09-03 09:57
# Fixed for SQLite compatibility using SeparateDatabaseAndState

from django.db import migrations, models


def drop_gin_index(apps, schema_editor):
    """
    Safely drop the GIN index only on PostgreSQL.
    On SQLite, the index was likely never created (skipped by Django),
    so attempting to drop it might cause 'no such index' or tokenizer errors.
    """
    if schema_editor.connection.vendor == 'postgresql':
        try:
            schema_editor.execute('DROP INDEX IF EXISTS "core_pdffil_search__1650a6_gin"')
        except Exception as e:
            print(f"Warning: Could not drop index on PostgreSQL: {e}")
    else:
        print("Skipping index removal on non-PostgreSQL backend (SQLite safe)")

class Migration(migrations.Migration):
    """
    Migration 0007: Remove PostgreSQL-specific search fields and add text_content.
    
    Refactored to be safe for SQLite by using RunPython for conditional index dropping.
    """

    dependencies = [
        ('core', '0006_pdffile_content_pdffile_search_vector_and_more'),
    ]

    operations = [
        # Step 1: Remove index - use SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Update Django's state to remove the index
                migrations.RemoveIndex(
                    model_name='pdffile',
                    name='core_pdffil_search__1650a6_gin',
                ),
            ],
            database_operations=[
                # Only run on PostgreSQL - on SQLite index was never created
                migrations.RunPython(drop_gin_index, reverse_code=migrations.RunPython.noop),
            ],
        ),
        
        # Step 2: Remove fields and add new one
        # These work on both SQLite and PostgreSQL
        migrations.RemoveField(
            model_name='pdffile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
