# Generated by Django 4.2.23 on 2025-11-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_folder_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='chunk_embeddings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='page_chunks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
