# Generated by Django 4.2.23 on 2026-02-24 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pdffile_chunk_embeddings_pdffile_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='category',
            field=models.CharField(blank=True, help_text='acts / rules / bylaws', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='file_path',
            field=models.CharField(blank=True, help_text='Relative path like housing/acts/154B.pdf', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='indexed',
            field=models.BooleanField(default=False, help_text='FAISS index built or not'),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='subject',
            field=models.CharField(blank=True, help_text='housing / audit / agriculture', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
