# Generated by Django 5.2.1 on 2026-07-23

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_pdffile_category_pdffile_file_path_pdffile_indexed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactGeneration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("generation_id", models.CharField(max_length=120, unique=True)),
                ("status", models.CharField(choices=[("staged", "Staged"), ("validated", "Validated"), ("active", "Active"), ("failed", "Failed")], default="staged", max_length=20)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(default="local", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="artifact_generations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="MaintenanceJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("kind", models.CharField(choices=[("validate", "Validate data"), ("reindex_needed", "Reindex needed"), ("reindex_all", "Reindex all"), ("repair_indexes", "Repair stored indexes"), ("sync_generation", "Sync generation"), ("restore_generation", "Restore generation")], max_length=32)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("paused", "Paused"), ("cancel_requested", "Cancel requested"), ("completed", "Completed"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=24)),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("completed_items", models.PositiveIntegerField(default=0)),
                ("failed_items", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="MaintenanceJobItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("skipped", "Skipped")], default="queued", max_length=16)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("folder", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_items", to="core.folder")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="core.maintenancejob")),
                ("pdf", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_items", to="core.pdffile")),
            ],
        ),
        migrations.AddConstraint(
            model_name="maintenancejobitem",
            constraint=models.UniqueConstraint(fields=("job", "pdf"), name="unique_maintenance_pdf_per_job"),
        ),
        migrations.AddIndex(model_name="maintenancejob", index=models.Index(fields=["status", "created_at"], name="core_mainte_status_e2695f_idx")),
        migrations.AddIndex(model_name="maintenancejob", index=models.Index(fields=["kind", "created_at"], name="core_mainte_kind_9e679b_idx")),
        migrations.AddIndex(model_name="maintenancejobitem", index=models.Index(fields=["job", "status"], name="core_mainte_job_id_865da0_idx")),
    ]
