# Generated by Django 5.2.16 on 2026-07-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pdffile_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceauditevent',
            name='event_type',
            field=models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('item_completed', 'Item completed'), ('item_failed', 'Item failed'), ('cancelled', 'Cancelled'), ('retried', 'Retried'), ('completed', 'Completed'), ('failed', 'Failed'), ('promoted', 'Promoted'), ('rolled_back', 'Rolled back'), ('purged', 'Purged'), ('worker_died', 'Worker died')], max_length=24),
        ),
    ]
