# Generated by Django 5.2

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_backfill_superuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancejob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("validate", "Validate data"),
                    ("reindex_needed", "Reindex needed"),
                    ("reindex_all", "Reindex all"),
                    ("reindex_selected", "Reindex selected"),
                    ("repair_indexes", "Repair stored indexes"),
                    ("sync_generation", "Sync generation"),
                    ("restore_generation", "Restore generation"),
                    ("promote_generation", "Promote generation"),
                    ("rollback_generation", "Rollback generation"),
                    ("purge_generation", "Purge generation"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("operation", models.CharField(choices=[("validate", "Validate files"), ("repair_indexes", "Repair stored indexes"), ("reindex_needed", "Reindex needed"), ("reindex_selected", "Reindex selected")], max_length=32)),
                ("state", models.CharField(choices=[("previewed", "Previewed"), ("queued", "Queued"), ("expired", "Expired"), ("rejected", "Rejected")], default="previewed", max_length=16)),
                ("selection", models.JSONField(default=dict)),
                ("preview", models.JSONField(default=dict)),
                ("source_digest", models.CharField(max_length=64)),
                ("state_version", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("external_embeddings_required", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_plans", to=settings.AUTH_USER_MODEL)),
                ("job", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_plan", to="core.maintenancejob")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="maintenanceplan",
            index=models.Index(fields=["state", "expires_at"], name="core_mainte_state_027063_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenanceplan",
            index=models.Index(fields=["created_by", "created_at"], name="core_mainte_created_d01a88_idx"),
        ),
    ]
