# Generated by Django 5.2.16 on 2026-07-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_maintenanceplan_operation_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceauditevent',
            name='event_type',
            field=models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('item_completed', 'Item completed'), ('item_failed', 'Item failed'), ('cancelled', 'Cancelled'), ('retried', 'Retried'), ('completed', 'Completed'), ('failed', 'Failed'), ('promoted', 'Promoted'), ('rolled_back', 'Rolled back'), ('purged', 'Purged'), ('worker_died', 'Worker died'), ('media_unavailable', 'Media unavailable'), ('media_restored', 'Media restored')], max_length=24),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='lifecycle',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('deprecated', 'Deprecated'), ('archived', 'Archived'), ('unavailable', 'Unavailable')], default='uploaded', help_text='Document lifecycle state for search and visibility control', max_length=20),
        ),
    ]
