# Generated by Django 5.2.16 on 2026-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pdffile_media_quarantine_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceauditevent',
            name='event_type',
            field=models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('item_completed', 'Item completed'), ('item_failed', 'Item failed'), ('cancelled', 'Cancelled'), ('retried', 'Retried'), ('completed', 'Completed'), ('failed', 'Failed'), ('promoted', 'Promoted'), ('rolled_back', 'Rolled back'), ('purged', 'Purged'), ('worker_died', 'Worker died'), ('media_unavailable', 'Media unavailable'), ('media_evidence_bound', 'Media recovery evidence bound'), ('media_restored', 'Media restored')], max_length=24),
        ),
    ]
