from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                ("role", models.CharField(choices=[("backup", "Backup"), ("restore", "Restore"), ("both", "Backup and restore")], default="both", max_length=8)),
                ("source", models.CharField(choices=[("environment", "Environment"), ("stored", "Stored fallback")], default="stored", max_length=16)),
                ("enabled", models.BooleanField(default=True)),
                ("environment_locked", models.BooleanField(default=False)),
                ("endpoint", models.CharField(blank=True, default="", max_length=500)),
                ("bucket", models.CharField(max_length=255)),
                ("region", models.CharField(blank=True, default="", max_length=80)),
                ("dataset_id", models.CharField(max_length=120)),
                ("source_id", models.CharField(blank=True, default="", max_length=120)),
                ("credential_prefix", models.CharField(blank=True, default="", max_length=120)),
                ("fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("last_observed_at", models.DateTimeField(blank=True, null=True)),
                ("observation", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ["key"]},
        ),
        migrations.CreateModel(
            name="DataOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("kind", models.CharField(choices=[("health_refresh", "Health refresh"), ("backup", "Backup"), ("restore", "Restore"), ("reindex", "Reindex"), ("auto_heal", "Automatic recovery")], max_length=24)),
                ("state", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("cancelled", "Cancelled"), ("waiting_approval", "Waiting for approval")], default="queued", max_length=20)),
                ("profile_key", models.SlugField(blank=True, default="", max_length=80)),
                ("request_id", models.CharField(blank=True, default="", max_length=160)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=160)),
                ("checkpoint", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RecoveryPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile_key", models.SlugField(max_length=80)),
                ("dataset_id", models.CharField(max_length=120)),
                ("release_id", models.CharField(max_length=160)),
                ("format_version", models.PositiveSmallIntegerField(default=1)),
                ("prefix", models.CharField(max_length=500)),
                ("manifest_digest", models.CharField(max_length=64)),
                ("state", models.CharField(choices=[("discovered", "Discovered"), ("verified", "Verified"), ("quarantined", "Quarantined"), ("invalid", "Invalid")], default="discovered", max_length=16)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("identity", models.JSONField(blank=True, default=dict)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DataCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_key_ciphertext", models.TextField(blank=True, default="")),
                ("secret_ciphertext", models.TextField(blank=True, default="")),
                ("nonce", models.CharField(blank=True, default="", max_length=64)),
                ("key_version", models.PositiveSmallIntegerField(default=1)),
                ("enabled", models.BooleanField(default=False)),
                ("last_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="credential", to="dataops.dataprofile")),
            ],
        ),
        migrations.CreateModel(
            name="DataOpsAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("actor_name", models.CharField(blank=True, default="", max_length=150)),
                ("action", models.CharField(max_length=80)),
                ("operation_id", models.UUIDField(blank=True, null=True)),
                ("profile_key", models.SlugField(blank=True, default="", max_length=80)),
                ("outcome", models.CharField(default="recorded", max_length=24)),
                ("evidence", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RestoreCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("environment", models.CharField(default="stage", max_length=32)),
                ("workspace", models.CharField(max_length=500)),
                ("state", models.CharField(choices=[("quarantined", "Quarantined"), ("verified", "Verified"), ("ready", "Ready for activation"), ("activated", "Activated"), ("rejected", "Rejected")], default="quarantined", max_length=16)),
                ("manifest_digest", models.CharField(max_length=64)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("operation", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="restore_candidate", to="dataops.dataoperation")),
                ("recovery_point", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="candidates", to="dataops.recoverypoint")),
            ],
        ),
        migrations.AddIndex(model_name="dataprofile", index=models.Index(fields=["role", "enabled"], name="dataops_dat_role_2d8c2f_idx")),
        migrations.AddIndex(model_name="dataoperation", index=models.Index(fields=["state", "kind"], name="dataops_dat_state_238b21_idx")),
        migrations.AddIndex(model_name="dataopsauditevent", index=models.Index(fields=["action", "created_at"], name="dataops_dat_action_5a4e54_idx")),
        migrations.AddConstraint(model_name="dataoperation", constraint=models.UniqueConstraint(condition=~models.Q(idempotency_key=""), fields=("kind", "idempotency_key"), name="dataops_unique_operation_idempotency")),
        migrations.AddConstraint(model_name="recoverypoint", constraint=models.UniqueConstraint(fields=("profile_key", "dataset_id", "release_id"), name="dataops_unique_recovery_point")),
    ]
